---
count: 6
default:
  restart: 0
  wait: 1
editor:
  files:
    bin:
      - bin/vcsw
      - bin/vcsvimdiff
    base:
      - lib/VCS/Which.pm
      - lib/VCS/Which/Plugin.pm
    plugins:
      - lib/VCS/Which/Plugin/CVS.pm
      - lib/VCS/Which/Plugin/Bazaar.pm
      - lib/VCS/Which/Plugin/Subversion.pm
      - lib/VCS/Which/Plugin/Git.pm
    t:
      - t/lib/VCS/Which/Plugin/Blank.pm
      - t/which.t
name: vcsw
terminals:
  1a:
    command: ./Build && ./Build testcover
    restart: 1
    wait: 0
    watch:
      - lib
      - bin
      - tests
  2:
    restart: 1
    edit: bin
  3:
    edit: base
  4:
    edit: plugins
  5:
    edit: t
