---
name: VCS-Which
version: 0.0.1
author:
  - 'Ivan Wills <ivan.wills@gmail.com>'
abstract: "<One-line description of module's purpose>"
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  perl: 5.008
build_requires:
  Test::More: 0
provides:
  VCS::Which:
    file: lib/VCS/Which.pm
    version: 0.0.1
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
